services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433: 5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - airflow_network

networks:
  airflow_network:
    external: false

volumes:
  postgres_data:
    